name: Android CI/CD Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: WeatherNL.Apk
          path: app/build/outputs/apk/debug/app-debug.apk